### ISSUE TITLE
Raindrop Issues for ThirteenAG

### ISSUE THREAD

**Issue by Noskillx** [aap/skygfx#11]
- Raindroples don't appear from firetruck "splash" when it hits you with the water or its near you.
- Blood Drops don't appear when you kill someone with a knife from the back... (Silent Kill)
- Raindroples from destroying hydrant shows even if you are long distance from them.
- Raindroples show when you push the car from the cliff in a long distance from water but they still appear (distance fix should be done)

**Comment by Keith94** [comment]
@ThirteenAG Have you seen these issues before? Just making sure you didn't miss it.

**Comment by ThirteenAG** [comment]
@Keith94 It's pretty clear to me that my contributions aren't welcome here (for various reasons), so I doubt I will be working on that.

**Comment by Keith94** [comment]
Well that's a shame.. I had no idea that was a thing. :-(

**Comment by aap** [comment]
I think things are fixed now...
