### ISSUE TITLE
[VC] Sky are completely black after installing this

### ISSUE THREAD

**Issue by dannetzy** [aap/skygfx#23]
Title say it all.
![image](https://user-images.githubusercontent.com/70806096/112087503-a8fbfb80-8bc0-11eb-822f-fb9055ff81aa.png)
When not using it.
![image](https://user-images.githubusercontent.com/70806096/112087670-f8422c00-8bc0-11eb-84ba-08a0f0111971.png)

**Comment by aap** [comment]
never seen this. no idea. i can only assume it's some clash of mods.

**Comment by dannetzy** [comment]
Nevermind this is caused by windowed mode. 
Edit:
I think I'll close it.
