### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Tiagoquix** [aap/skygfx#29]
Licenses are important. You should have one.

Read here about what happens when you don't have a license: https://choosealicense.com/no-permission/

I recommend the MIT License. You can read more about the other licenses here: https://choosealicense.com/licenses/

**Comment by mshcherbyna99** [comment]
Hey @aap!

It would be great if you could add a license to your SkyGFX mod. Without one, people might be unsure about using or contributing to it.

The MIT License, which was mentioned by @ThirteenAG is super easy and a solid choice.
