### ISSUE TITLE
[GTASA] neoWaterDrops artifacts

### ISSUE THREAD

**Issue by Blackbird88** [aap/skygfx#5]
Happens when camera is moved a lot.
![image](https://cloud.githubusercontent.com/assets/4414625/23276487/c89c43a6-fa0a-11e6-8b84-7540dbf2e373.png)

**Comment by aap** [comment]
Haven't been able to reproduce...maybe I haven't moved the camera enough? Can you make a video?

**Comment by Blackbird88** [comment]
Took me a while to reproduce. Not sure what causes it
https://www.youtube.com/watch?v=r6aMkPe4jCE

**Comment by aap** [comment]
Looks like some renderstates having to do with transformation are leaking. I'll check it out soon.

**Comment by Blackbird88** [comment]
Here
http://www27.zippyshare.com/v/cXg1XVtd/file.html

**Comment by Blackbird88** [comment]
@aap 
@ThirteenAG  says you ignored my PIX frame :(

**Comment by aap** [comment]
Hadn't looked at it at the time and now that I'm working on it again the file has expired.

**Comment by Blackbird88** [comment]
[pix_rain.zip](https://github.com/aap/skygfx/files/1117703/pix_rain.zip)

**Comment by aap** [comment]
The first two frames look fine for me, the third one seems to be incomplete.

**Comment by Blackbird88** [comment]
I forgot to mention there's also some leak or something cause the game crashes eventually if it rains.

**Comment by Blackbird88** [comment]
So am I only one getting the crash?

**Comment by Blackbird88** [comment]
My game is running at 60 FPS so getting to the 14K frames is much faster. idk if that matters.

**Comment by Blackbird88** [comment]
Crash only appears in 32150c5

- TextInputFramework.dll!`Microsoft::WRL::Module<1,class Microsoft::WRL::Details::DefaultModule<1> ::Create(void)'::`2'::`dynamic atexit destructor for 'moduleSingleton''(void)	Unknown 	

- TextInputFramework.dll!CTextInputClientFreeThread::PutHasFocus(bool)	Unknown

Latest version seems fine so I'm closing this for now.
