### ISSUE TITLE
Lights show up as squares

### ISSUE THREAD

**Issue by Logics4** [aap/skygfx#8]
Hello.
I've been using this mod since some time, however during all this time I always had a bug that I decided to report now, since 3.3 just came out and I still have this problem.
This bug usually happens to me during specific times in GTA, in specific weathers, so, to take some screenshots, I used a mod to lock the time and weather to a specific value.

![ps2](https://user-images.githubusercontent.com/25278238/28984478-0ea2f76c-7956-11e7-8100-58b6f8a75aec.png)
This bug seems to happen when I have the vehiclePipe set to PS2 (although I realized it also happens when it's set to Neo and Spec). When I have it set to PS2, these squares appear in the place of the vehicle lights and the lights from the street poles. When I have it set to PC or Xbox the lights seem to show up normally.
In this case I locked the time to 2:00 and set the weather to "FOGGY_SF" (http://wiki.sa-mp.com/wiki/WeatherID).
Also, I only see these squares depending on the angle.

It also happens inside the car:
![ps2-2](https://user-images.githubusercontent.com/25278238/28984607-c8629932-7956-11e7-8655-4aac427a7bf8.png)
I also usually see them when I'm driving.

![ps2-3](https://user-images.githubusercontent.com/25278238/28984657-fb0bc17e-7956-11e7-8e5f-8dbb2556948a.png)
In this case I locked the time to 21:00 and set the weather to "EXTRASUNNY_LA". It also happens this bug, although on the image it seems the squares are more transparent, I just couldn't get a better example, sorry.
Can you fix this, please?

**Comment by aap** [comment]
That's a well known issue. It's caused by samprestore.

**Comment by Logics4** [comment]
SAMPGraphicRestore? Well, I didn't know.
I've been using SAGFX: PS2 mod for the car reflections, however the reflections were too "deep" and I found SkyGfx's reflections nicer. I don't have that bug with SAGFX.
But if I don't use SAMPGraphicRestore, wouldn't SkyGfx not work on samp?
